# Generated by Django 5.2.8 on 2025-11-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Check this if the article is primarily a video.', verbose_name='Video Post'),
        ),
    ]
